### ISSUE TITLE
features request: expandText position, margin and text ellipsize

### ISSUE THREAD

**Issue by alexodus** [oktayayr/advancedtextview#1]
It would be nice if we could have these feature:
- expandText position (left, center, right)
- expandText margin (or use the same of the text): now if I use layout_marginLeft the expandText isn't aligned to it
- text ellipsize (...)

**Comment by oktayayr** [comment]
Thank you for your recommendations. These options will be available next version

**Comment by oktayayr** [comment]
These features have been added with 0.3.0
