### ISSUE TITLE
Error:Execution failed for task ':app:packageDebug'.> java.io.FileNotFoundException: H:\Project\MyApp\app\build\intermediates\assets\debug\fonts (Access is denied)

### ISSUE THREAD

**Issue by yudhir** [oktayayr/advancedtextview#4]
Error:Execution failed for task ':app:packageDebug'.> java.io.FileNotFoundException: H:\Project\My App\app\build\intermediates\assets\debug\fonts (Access is denied).

I received this error .
But then I created Assets Folder .

Solved

**Comment by anhtata** [comment]
I got the same issue and solve by using rimraf (nodejs lib) to clean up build folder in H:\Project\My App\app\
